#Get all categories
# GET {{DATABASE_URL}}/get-categories
GET {{DATABASE_URL}}/get-categories
Content-Type: application/json
###

#Add only one category
POST {{DATABASE_URL}}/create-category
Content-Type: application/json

{
  "name": "sports",
  "namePt": "Esportes"
}
###

#Add many categories
POST {{DATABASE_URL}}/create-categories
Content-Type: application/json

[
  {
    "name": "actionAdventure",
    "namePt": "Ação e aventura"
  },
  {
    "name": "rpgOpenWorld",
    "namePt": "RPG de mundo aberto"
  },
  {
    "name": "rpgTurnBased",
    "namePt": "RPG de turnos"
  },
  {
    "name": "actionTerror",
    "namePt": "Ação e terror"
  },
  {
    "name": "fps",
    "namePt": "Tiro em primeira pessoa"
  },
  {
    "name": "survivalHorror",
    "namePt": "Survival Horror"
  },
  {
    "name": "racing",
    "namePt": "Corrida"
  },
  {
    "name": "actionRhythm",
    "namePt": "Ação e ritmo"
  },
  {
    "name": "metroidvania",
    "namePt": "Metroidvania"
  },
  {
    "name": "souslike",
    "namePt": "Soulslike"
  },
  {
  "name": "sports",
  "namePt": "Esportes"
  }
]
###