#Add a new evaluation
POST http://localhost:3003/add-evaluation
Content-Type: application/json

{
  "description": "jogo bom mas muito bugado, crasha toda hora",
  "stars": 2,
  "productId": 2,
  "userId": 1
}
###

#Get one game evaluations
GET http://localhost:3003/get-game-evaluations/82
Content-Type: application/json
###

#Get user evaluations
GET http://localhost:3003/get-user-evaluations/1
Content-Type: application/json
###

#Get one user evaluation
GET http://localhost:3003/get-user-evaluations/21
Content-Type: application/json
Cookie: gamingPlatformAuth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJwZWRyb0BnbWFpbC5jb20iLCJuYW1lIjoiUGVkcm8gU2FudGFuYSIsInBob25lIjoiKDMxKSA5OTg2OS01MjE5IiwiaWF0IjoxNzA1Mzc0ODcwLCJleHAiOjE3MDU5Nzk2NzB9.2OYxxP1fmmYygYGDOg29KSd8tTKc3AwFI0o7G2MOH2c
###
