#Add only one new game
POST {{DATABASE_URL}}/add-game
Content-Type: application/json

{
  "name": "Call Of Duty: Black Ops 6",
  "categoryId": 5,
  "price": 349.9,
  "image":
    "https://www.callofduty.com/content/dam/atvi/callofduty/cod-touchui/blog/hero/bo6/COD-UNREDACTED-004.jpg",
  "description":
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}
###

#Add many new games
POST {{DATABASE_URL}}/add-many-games
Content-Type: application/json

[
  {
    "name": "Red Dead Redemption 2",
    "categoryId": 1,
    "price": 249,
    "image": "https://howlongtobeat.com/games/27100_Red_Dead_Redemption_2.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Cyberpunk 2077 Complete Edition",
    "categoryId": 2,
    "price": 299,
    "image": "https://howlongtobeat.com/games/Cyberpunk-2077-2.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Baldur's Gate 3",
    "categoryId": 3,
    "price": 199,
    "image": "https://howlongtobeat.com/games/68033_Baldurs_Gate_3.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Dead Space Remake",
    "categoryId": 4,
    "price": 249,
    "image": "https://howlongtobeat.com/games/95927_Dead_Space.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Battlefield 2042",
    "categoryId": 5,
    "price": 199,
    "image": "https://howlongtobeat.com/games/93426_Battlefield_2042.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Starfield",
    "categoryId": 2,
    "price": 279,
    "image": "https://howlongtobeat.com/games/57445_Starfield.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Grand Theft Auto VI",
    "categoryId": 1,
    "price": 349,
    "image": "https://howlongtobeat.com/games/104609_Grand_Theft_Auto_VI.png",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Call Of Duty: MODERN WARFARE III",
    "categoryId": 5,
    "price": 349,
    "image": "https://howlongtobeat.com/games/132689_Call_of_Duty_Modern_Warfare_III.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Alan Wake II",
    "categoryId": 6,
    "price": 249,
    "image": "https://howlongtobeat.com/games/101237_Alan_Wake_2.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "The Witcher 3",
    "categoryId": 2,
    "price": 249,
    "image": "https://howlongtobeat.com/games/10270_The_Witcher_3_Wild_Hunt.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Resident Evil 4 Remake",
    "categoryId": 6,
    "price": 199,
    "image": "https://howlongtobeat.com/games/108881_Resident_Evil_4.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Forza Motorsport",
    "categoryId": 7,
    "price": 299,
    "image": "https://howlongtobeat.com/games/109240_Forza_Motorsport.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "God of War Ragnarok",
    "categoryId": 1,
    "price": 349,
    "image": "https://howlongtobeat.com/games/83146_God_of_War_Ragnark.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Hi-Fi Rush",
    "categoryId": 8,
    "price": 89,
    "image": "https://howlongtobeat.com/games/122891_Hi-Fi_Rush.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Forza Horizon 5",
    "categoryId": 7,
    "price": 249,
    "image": "https://howlongtobeat.com/games/93948_Forza_Horizon_5.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Horizon Forbidden West",
    "categoryId": 2,
    "price": 299,
    "image": "https://howlongtobeat.com/games/79775_Horizon_Forbidden_West.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T17:51:31.809Z"
  },
  {
    "name": "Ori and the Will of the Wisps",
    "categoryId": 9,
    "price": 99,
    "image": "https://howlongtobeat.com/games/46428_Ori_and_the_Will_of_the_Wisps.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T18:03:05.114Z"
  },
  {
    "name": "Senua's Saga: Hellblade II",
    "categoryId": 1,
    "price": 229.9,
    "image": "https://howlongtobeat.com/games/72854_Senuas_Saga_Hellblade_II.jpg",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "created_at": "2024-01-10T18:07:47.977Z"
  },
  {
    "name": "Elden Ring",
    "categoryId": 10,
    "price": 249.9,
    "image":
      "https://howlongtobeat.com/games/68151_Elden_Ring.jpg",
    "description":
      "Estados Unidos, 1899. O fim da era do velho oeste se aproxima, e os xerifes caçam as últimas gangues fora da lei. Quem não se rende ou sucumbe, acaba morto. Depois de tudo dar errado em um roubo na cidade de Blackwater, no faroeste, Arthur Morgan e a gangue Van der Linde são obrigados a fugir."
  },
  {
  "name": "EA SPORTS FC 24",
  "categoryId": 11,
  "price": 299.9,
  "image":
    "https://howlongtobeat.com/games/131658_EA_Sports_FC_24.jpg",
  "description":
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
  }
]
###

#Get all games
GET {{DATABASE_URL}}/get-games
Content-Type: application/json
###

#Get games with optional query params 'busca' or '(category=true)'
GET {{DATABASE_URL}}/get-games?busca=forza
Content-Type: application/json
###

#Get one game by gameId
GET {{DATABASE_URL}}/get-game/6
Content-Type: application/json
###

#Get one game by name
GET {{DATABASE_URL}}/get-game-by-name/starfield
Content-Type: application/json
###