#User login
POST https://gaming-ecommerce-backend.onrender.com/login
Content-Type: application/json

{
  "email": "pedro@gmail.com",
  "password": "02089999"
}
###

#User logout
POST https://gaming-ecommerce-backend.onrender.com/logout
Content-Type: application/json
###