#User login
POST {{DATABASE_URL}}/login
Content-Type: application/json

{
  "email": "pedro@gmail.com",
  "password": "02089999"
}
###

#User logout
POST {{DATABASE_URL}}/logout
Content-Type: application/json
###