#User login
POST {{API_URL}}/login
Content-Type: application/json

{
  "email": "pedro@gmail.com",
  "password": "02089999"
}
###

#User logout
POST {{API_URL}}/logout
Content-Type: application/json
###